name: ğŸŒ Deploy Vless Worker

on:
  workflow_dispatch:
    inputs:
      WORKER_NAME:
        description: "ğŸŒŸ Name of your worker"
        required: true
        type: string
      DOMAIN_NAME:
        description: "ğŸ  Domain Name on Cloudflare"
        required: false
        type: string
        default: gpj.us.kg

jobs:
  deploy:
    name: ğŸš€ Deploy Cloudflare Worker
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout repository
      - name: ğŸ“‚ Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install Node.js
      - name: ğŸ› ï¸ Install Node.js (LTS)
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      # Step 3: Install Wrangler
      - name: ğŸ”„ Install Wrangler
        run: npm install -g wrangler

      # Step 4: Obfuscate Worker Code
      - name: ğŸ”’ Obfuscate _worker.js
        run: |
          npm install -g javascript-obfuscator
          javascript-obfuscator vless/_worker.js --output vless/_worker_obfuscated.js \
            --compact true \
            --control-flow-flattening true \
            --control-flow-flattening-threshold 1 \
            --dead-code-injection true \
            --dead-code-injection-threshold 1 \
            --identifier-names-generator hexadecimal \
            --rename-globals true \
            --string-array true \
            --string-array-encoding 'rc4' \
            --string-array-threshold 1 \
            --transform-object-keys true \
            --unicode-escape-sequence true

      # Step 5: Replace _worker.js with obfuscated version
      - name: ğŸ”„ Replace _worker.js with obfuscated version
        run: |
          mv vless/_worker_obfuscated.js vless/_worker.js

      # Step 6: Process Configuration
      - name: ğŸ”§ Update Configuration
        run: |
          WORKER_NAME=${{ github.event.inputs.WORKER_NAME }}
          DOMAIN_NAME=${{ github.event.inputs.DOMAIN_NAME }}

          echo "Updating WORKER_NAME to ${WORKER_NAME}"
          sed -i "s/%worker_name%/${WORKER_NAME}/g" ./vless/wrangler.toml
          echo "Updating DOMAIN_NAME to ${DOMAIN_NAME}"
          sed -i "s/%domain_name%/${DOMAIN_NAME}/g" ./vless/wrangler.toml

      # Step 7: Deploy the Worker
      - name: ğŸš€ Deploy to Cloudflare
        run: |
          cd vless
          wrangler deploy --name ${{ github.event.inputs.WORKER_NAME }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
